'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, Eye, EyeOff, Save, Trash2 } from 'lucide-react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

const slugify=(v:string)=>v.toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const providers=['Hotmart','Kiwify','Eduzz','Shopify','WhatsApp','Other']; const currencies=['AOA','USD','EUR','BRL'];
export default function EditProduct(){const {id}=useParams<{id:string}>(); const router=useRouter(); const [org,setOrg]=useState(''); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [price,setPrice]=useState(''); const [currency,setCurrency]=useState('AOA'); const [url,setUrl]=useState(''); const [provider,setProvider]=useState('Other'); const [category,setCategory]=useState(''); const [published,setPublished]=useState(false); const [featured,setFeatured]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.replace('/login');return;}const {data:m}=await s.from('organization_members').select('organization_id').eq('user_id',user.id).limit(1).maybeSingle();if(!m?.organization_id){router.replace('/onboarding');return;}setOrg(m.organization_id);const {data:p,error:e}=await s.from('products').select('*,categories(name)').eq('id',id).eq('organization_id',m.organization_id).single();if(e||!p){setError('Product not found.');return;}setName(p.name);setDescription(p.description||'');setPrice(p.price==null?'':String(p.price));setCurrency(p.currency);setUrl(p.purchase_url);setProvider(p.provider||'Other');setCategory((p.categories as {name:string}|null)?.name||'');setPublished(p.is_published);setFeatured(p.is_featured);})();},[id,router]);
async function save(e:FormEvent){e.preventDefault();setError('');if(!name.trim()||!/^https:\/\//i.test(url.trim())){setError('Enter a product name and a secure HTTPS purchase link.');return;}setSaving(true);const s=createClient();let categoryId:null|string=null;if(category){const {data:c,error:ce}=await s.from('categories').upsert({organization_id:org,name:category,slug:slugify(category)},{onConflict:'organization_id,slug'}).select('id').single();if(ce){setError(ce.message);setSaving(false);return;}categoryId=c.id;}const {error:e2}=await s.from('products').update({name:name.trim(),slug:slugify(name)||id,description:description.trim()||null,price:price?Number(price):null,currency,purchase_url:url.trim(),provider,category_id:categoryId,is_published:published,is_featured:featured,updated_at:new Date().toISOString()}).eq('id',id).eq('organization_id',org);if(e2){setError(e2.message);setSaving(false);return;}router.push('/dashboard');router.refresh();}
async function remove(){if(!confirm('Delete this product permanently?'))return;setSaving(true);const s=createClient();const {error:e}=await s.from('products').delete().eq('id',id).eq('organization_id',org);if(e){setError(e.message);setSaving(false);return;}router.push('/dashboard');router.refresh();}
if(error&&!name)return <main className="form-page"><Link href="/dashboard" className="back-link"><ArrowLeft size={17}/> Back</Link><div className="form-error">{error}</div></main>;
return <main className="form-page"><div className="form-page-header"><Link href="/dashboard" className="back-link"><ArrowLeft size={17}/> Back to products</Link><div><h1>Edit product</h1><p>Update your product and control its visibility.</p></div></div><form className="product-form" onSubmit={save}><section className="form-panel"><h2>Product details</h2><label>Product name<span>*</span><input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Description <em>Optional</em><textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="two-col"><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">None</option>{['Curso','Ebook','Mentoria','Serviço','Outro'].map(x=><option key={x}>{x}</option>)}</select></label><label>Provider<select value={provider} onChange={e=>setProvider(e.target.value)}>{providers.map(x=><option key={x}>{x}</option>)}</select></label></div></section><section className="form-panel"><h2>Purchase</h2><label>Purchase link<span>*</span><input type="url" value={url} onChange={e=>setUrl(e.target.value)} required/></label><div className="two-col"><label>Price<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}>{currencies.map(x=><option key={x}>{x}</option>)}</select></label></div></section><section className="form-panel options"><label className="check"><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/><span><strong>Featured product</strong><small>Prioritize this product in the storefront.</small></span></label><label className="check"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/><span><strong>Published</strong><small>Show this product when the storefront is published.</small></span></label></section>{error&&<div className="form-error">{error}</div>}<div className="form-actions"><button type="button" className="danger" onClick={remove} disabled={saving}><Trash2 size={16}/> Delete</button><Link href="/dashboard">Cancel</Link><button className="primary" disabled={saving}><Save size={17}/>{saving?'Saving…':'Save changes'}</button></div></form></main>}
