'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ArrowRight, Check, Globe2, Store } from 'lucide-react';
import { useRouter } from 'next/navigation';
import styles from './onboarding.module.css';

const WELCOME_VIDEO = 'https://cdn.creativeclaw.co/u/51a597e8/videos/79ba29f5-88cd-4a18-8b58-8a9e2abd9d95.mp4';
const slugify = (value: string) => value.toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,40);

export default function OnboardingPage() {
  const router=useRouter();const [name,setName]=useState('');const [username,setUsername]=useState('');const [description,setDescription]=useState('');const [checking,setChecking]=useState(false);const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  useEffect(()=>{let mounted=true;(async()=>{try{const supabase=(await import('@/lib/supabase/client')).createClient();const {data:{user},error:authError}=await supabase.auth.getUser();if(authError)throw authError;if(!user){router.replace('/login?next=/onboarding');return;}const meta=user.user_metadata||{};if(mounted){setName(meta.organization_name||'');setUsername(meta.organization_slug||'');setDescription(meta.organization_description||'');}}catch(err){if(mounted)setError(err instanceof Error?err.message:'Não foi possível verificar a tua sessão.');}finally{if(mounted)setLoading(false);}})();return()=>{mounted=false;};},[router]);
  const setBrandName=(value:string)=>{setName(value);if(!username||username===slugify(name))setUsername(slugify(value));};
  async function submit(e:FormEvent){e.preventDefault();if(saving)return;setError('');const cleanName=name.trim(),cleanSlug=slugify(username);if(cleanName.length<2){setError('O nome deve ter pelo menos 2 caracteres.');return;}if(cleanSlug.length<3){setError('Escolhe um nome de utilizador com pelo menos 3 caracteres.');return;}setSaving(true);try{const supabase=(await import('@/lib/supabase/client')).createClient();const rpc=supabase.rpc('create_workspace',{workspace_name:cleanName,workspace_slug:cleanSlug,workspace_description:description.trim()||null});const timeout=new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('A criação demorou demasiado. Tenta novamente.')),12000));const {error:rpcError}=await Promise.race([rpc,timeout]);if(rpcError)throw rpcError;router.replace(`/store/${cleanSlug}`);router.refresh();}catch(err){setError(err instanceof Error?err.message:'Não foi possível criar a tua vitrine. Tenta novamente.');setSaving(false);}}
  async function checkUsername(){const slug=slugify(username);if(!slug)return;setChecking(true);setError('');try{const supabase=(await import('@/lib/supabase/client')).createClient();const {data,error:checkError}=await supabase.from('organizations').select('id').eq('slug',slug).maybeSingle();if(checkError)throw checkError;setError(data?'Esse nome de utilizador já está ocupado.':'✓ Nome de utilizador disponível');}catch{setError('Não foi possível verificar o nome agora.')}finally{setChecking(false);}}
  if(loading)return <main className={styles['onboarding-page']}><div className={styles['onboarding-card']}><video className={styles['onboarding-video']} autoPlay muted loop playsInline preload="auto" src={WELCOME_VIDEO} aria-label="Boas-vindas ao Product Hub"/><div className={styles['onboarding-brand']}><span className="hub-logo"><Store size={18}/></span><strong>Product Hub</strong></div><p>A verificar a tua sessão…</p></div></main>;
  return <main className={styles['onboarding-page']}><div className={styles['onboarding-card']}><div className={styles['onboarding-media']}><video className={styles['onboarding-video']} autoPlay muted loop playsInline preload="auto" src={WELCOME_VIDEO} aria-label="Boas-vindas ao Product Hub"/></div><div className={styles['onboarding-brand']}><span className="hub-logo"><Store size={18}/></span><strong>Product Hub</strong></div><div className={styles['onboarding-progress']}><span className={styles.done}><Check size={13}/></span><i/><span className={styles.current}>2</span><i/><span>3</span></div><div className={styles['onboarding-heading']}><span className={styles.eyebrow}>A TUA VITRINE</span><h1>Conta-nos sobre a tua marca.</h1><p>Esta informação será a identidade que as pessoas verão quando descobrirem os teus produtos.</p></div><form onSubmit={submit}><label>Nome da marca ou criador<span>*</span><input value={name} onChange={e=>setBrandName(e.target.value)} placeholder="João Silva" required minLength={2}/></label><label>Nome de utilizador da vitrine<span>*</span><div className={styles['username-input']}><span>producthub.store/@</span><input value={username} onChange={e=>setUsername(slugify(e.target.value))} placeholder="joao-silva" required minLength={3} maxLength={40}/><button type="button" onClick={checkUsername} disabled={checking}>{checking?'…':'Verificar'}</button></div></label><label>Descrição <em>Opcional</em><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Especialista em Marketing Digital" rows={3}/></label><div className={styles['onboarding-preview']}><div className={styles['preview-icon']}><Globe2 size={18}/></div><div><strong>A tua vitrine</strong><span>producthub.store/@{slugify(username)||'o-teu-nome'}</span></div></div>{error&&<div className={`${styles['onboarding-message']} ${error.startsWith('✓')?styles.success:''}`} role="alert">{error}</div>}<button type="submit" className={`primary ${styles['onboarding-submit']}`} disabled={saving}>{saving?'A criar a tua vitrine…':'Criar e abrir a vitrine'} <ArrowRight size={17}/></button></form><small>Podes alterar estes dados mais tarde em Definições.</small></div></main>;
}
