'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ArrowRight, Check, Globe2, Store } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';
import styles from './onboarding.module.css';

const slugify = (value: string) => value.toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,40);

export default function OnboardingPage() {
  const router=useRouter();const [name,setName]=useState('');const [username,setUsername]=useState('');const [description,setDescription]=useState('');const [checking,setChecking]=useState(false);const [saving,setSaving]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  useEffect(()=>{let mounted=true;(async()=>{try{const supabase=createClient();const {data:{user},error:authError}=await supabase.auth.getUser();if(authError)throw authError;if(!user){router.replace('/login');return;}}catch(err){if(mounted)setError(err instanceof Error?err.message:'Unable to verify your session.');}finally{if(mounted)setLoading(false);}})();return()=>{mounted=false;};},[router]);
  const setBrandName=(value:string)=>{setName(value);if(!username||username===slugify(name))setUsername(slugify(value));};
  async function submit(e:FormEvent){e.preventDefault();if(saving)return;setError('');const cleanName=name.trim(),cleanSlug=slugify(username);if(cleanName.length<2){setError('Brand or creator name must be at least 2 characters.');return;}if(cleanSlug.length<3){setError('Choose a username with at least 3 characters.');return;}setSaving(true);try{const supabase=createClient();const rpc=supabase.rpc('create_workspace',{workspace_name:cleanName,workspace_slug:cleanSlug,workspace_description:description.trim()||null});const timeout=new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('Workspace creation took too long. Please try again.')),12000));const {error:rpcError}=await Promise.race([rpc,timeout]);if(rpcError)throw rpcError;router.replace('/dashboard');router.refresh();}catch(err){setError(err instanceof Error?err.message:'Unable to create your storefront. Please try again.');setSaving(false);}}
  async function checkUsername(){const slug=slugify(username);if(!slug)return;setChecking(true);setError('');try{const supabase=createClient();const {data,error:checkError}=await supabase.from('organizations').select('id').eq('slug',slug).maybeSingle();if(checkError)throw checkError;setError(data?'That username is already taken.':'✓ Username available');}catch{setError('Could not check this username right now.')}finally{setChecking(false);}}
  if(loading)return <main className={styles['onboarding-page']}><div className={styles['onboarding-card']}><div className={styles['onboarding-brand']}><span className="hub-logo"><Store size={18}/></span><strong>Product Hub</strong></div><p>Checking your session…</p></div></main>;
  return <main className={styles['onboarding-page']}><div className={styles['onboarding-card']}><div className={styles['onboarding-brand']}><span className="hub-logo"><Store size={18}/></span><strong>Product Hub</strong></div><div className={styles['onboarding-progress']}><span className={styles.done}><Check size={13}/></span><i/><span className={styles.current}>2</span><i/><span>3</span></div><div className={styles['onboarding-heading']}><span className={styles.eyebrow}>YOUR STOREFRONT</span><h1>Tell us about your brand.</h1><p>This becomes the identity people see when they discover your products.</p></div><form onSubmit={submit}><label>Brand or creator name<span>*</span><input value={name} onChange={e=>setBrandName(e.target.value)} placeholder="João Silva" required minLength={2}/></label><label>Storefront username<span>*</span><div className={styles['username-input']}><span>producthub.store/@</span><input value={username} onChange={e=>setUsername(slugify(e.target.value))} placeholder="joao-silva" required minLength={3} maxLength={40}/><button type="button" onClick={checkUsername} disabled={checking}>{checking?'…':'Check'}</button></div></label><label>Description <em>Optional</em><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Especialista em Marketing Digital" rows={3}/></label><div className={styles['onboarding-preview']}><div className={styles['preview-icon']}><Globe2 size={18}/></div><div><strong>Your storefront</strong><span>producthub.store/@{slugify(username)||'your-name'}</span></div></div>{error&&<div className={`${styles['onboarding-message']} ${error.startsWith('✓')?styles.success:''}`} role="alert">{error}</div>}<button type="submit" className={`primary ${styles['onboarding-submit']}`} disabled={saving}>{saving?'Creating your storefront…':'Continue'} <ArrowRight size={17}/></button></form><small>You can change these details later in Settings.</small></div></main>;
}
