'use client';

import { Check, Lock, Sparkles, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

const plans = [
  { id:'free', name:'Free', price:'0', description:'Para começar e publicar a tua primeira vitrine.', features:['Vitrine pública','Até 10 produtos','Logo, nome e descrição','Cores essenciais','Grelha ou lista','Categorias','Analytics básico'], color:'#aeb8c8' },
  { id:'pro', name:'Pro', price:'€9', description:'Para negócios que querem controlo total sobre a apresentação e crescimento da marca.', features:['Tudo do Free','Produtos ilimitados','Temas premium','Banners profissionais','Cores e tipografia avançadas','Layouts avançados','Produtos em destaque','Seções promocionais','Mais estilos de cartões e botões','Remover marca Product Hub','Analytics avançado','Domínio personalizado do cliente'], color:'#c8d5ff' },
];

export default function BillingPage(){
 const [plan,setPlan]=useState('free'); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){setLoading(false);return}const {data:m}=await s.from('organization_members').select('organization_id').eq('user_id',user.id).limit(1).maybeSingle();if(m?.organization_id){const {data:b}=await s.from('organization_billing').select('plan').eq('organization_id',m.organization_id).maybeSingle();if(b?.plan)setPlan(b.plan)}setLoading(false)})()},[]);
 return <div className="app-shell"><main className="main-shell" style={{marginLeft:0,minHeight:'100vh'}}><div className="page-content" style={{maxWidth:1180,margin:'0 auto'}}><Link href="/dashboard" style={{display:'inline-flex',gap:8,alignItems:'center',color:'#9aa4b5',textDecoration:'none',marginBottom:28}}><ArrowLeft size={15}/> Voltar ao dashboard</Link><div className="page-heading"><div><span className="section-kicker">PLANOS</span><h1>Free ou Pro. Só precisas de escolher.</h1><p>O Free dá-te o essencial para começar. O Pro desbloqueia a experiência completa do Product Hub.</p></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:18,marginTop:30}}>{plans.map(p=><section key={p.id} className="panel" style={{padding:26,position:'relative',borderColor:plan===p.id?p.color:'rgba(255,255,255,.08)'}}>{plan===p.id&&<div style={{position:'absolute',top:18,right:18,fontSize:11,color:p.color}}>PLANO ATUAL</div>}<Sparkles size={20} style={{color:p.color}}/><h2 style={{margin:'18px 0 8px',fontSize:24}}>{p.name}</h2><div style={{fontSize:38,fontWeight:700}}>{p.price}<small style={{fontSize:14,color:'#7f8795'}}>{p.id==='free'?'':' / mês'}</small></div><p style={{color:'#8b94a3',minHeight:52,lineHeight:1.5}}>{p.description}</p><div style={{display:'grid',gap:12,marginTop:22}}>{p.features.map(f=><div key={f} style={{display:'flex',gap:9,alignItems:'flex-start',color:'#d7dce5',fontSize:14}}><Check size={16} style={{color:p.color,flex:'0 0 auto',marginTop:1}}/>{f}</div>)}</div><button disabled={loading||p.id===plan} style={{marginTop:26,width:'100%',padding:'12px 15px',borderRadius:11,border:'1px solid rgba(255,255,255,.09)',background:p.id===plan?'rgba(255,255,255,.05)':'#eef2fb',color:p.id===plan?'#7d8796':'#0b0d11',fontWeight:700,cursor:p.id===plan?'default':'pointer'}}>{p.id===plan?'Plano atual':'Em breve — pagamentos'}</button></section>)}</div><div className="panel" style={{marginTop:22,padding:20,color:'#9ca5b4'}}><Lock size={15} style={{verticalAlign:'-2px',marginRight:8}}/>O checkout ainda não está ativo. Esta área apenas apresenta a arquitetura de planos; a cobrança real será ligada numa etapa separada.</div></div></main></div>
}
