'use client';

import Link from 'next/link';
import { BadgeCheck, Check, LockKeyhole, Palette, Store, BarChart3, Package, Globe2, SlidersHorizontal } from 'lucide-react';

const free=['Vitrine pública','Até 10 produtos','Logo, nome e descrição','Cores base','Layout grelha ou lista','Categorias básicas','Analytics básico'];
const pro=['Produtos ilimitados','Temas premium','Cores e tipografia avançadas','Layouts avançados','Banners e promoções','Produtos em destaque','Analytics avançado','Remover branding Product Hub','Domínio personalizado','Estilos avançados de cartões e botões'];

export default function SettingsPage(){
 return <main className="settings-page"><div className="settings-wrap"><div className="page-heading"><div><span className="section-kicker">CONFIGURAÇÃO</span><h1>Definições</h1><p>Controla a tua conta, a tua vitrine e o plano do Product Hub num só lugar.</p></div></div><div className="settings-plan-intro"><div><span className="settings-plan-kicker">DO FREE AO PRO</span><h2>Escolhe o nível de controlo que combina com o teu negócio.</h2><p>As funcionalidades estão organizadas por plano para ficares sempre a saber o que tens disponível.</p></div><div className="settings-plan-badge"><BadgeCheck size={16}/> PRO</div></div><section className="settings-grid"><article className="setting-card"><div className="setting-icon"><Store size={19}/></div><div><h2>Personalizar vitrine</h2><p>Logo, identidade, cores, layout, cartões, botões, tipografia, categorias, destaques e conteúdo avançado.</p><Link className="primary" href="/dashboard?tab=storefront">Abrir personalizador</Link></div></article><article className="setting-card"><div className="setting-icon"><Palette size={19}/></div><div><h2>Identidade visual</h2><p>Uma base visual clara e contemporânea, com cor usada para hierarquia e ações — sem estética genérica de IA.</p><span className="setting-note">Sistema multicolor organizado</span></div></article><article className="setting-card plan-free"><div className="setting-icon"><Package size={19}/></div><div><div className="plan-label">FREE</div><h2>Plano Free</h2><p>O essencial para colocar a tua vitrine no ar e começar a vender.</p><ul>{free.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul></div></article><article className="setting-card pro-card"><div className="setting-icon pro-icon"><BadgeCheck size={19}/></div><div><div className="plan-label pro-label">PRO</div><h2>Plano Pro</h2><p>Uma camada premium para quem quer mais liberdade visual, comercial e de análise.</p><ul>{pro.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><Link className="primary pro-action" href="/dashboard/billing">Ver opções Pro</Link></div></article><article className="setting-card"><div className="setting-icon"><BarChart3 size={19}/></div><div><h2>Analytics</h2><p>Visitas, visualizações, cliques, CTR, funil e desempenho por produto continuam centralizados na área Analytics.</p><span className="setting-note"><SlidersHorizontal size={14}/> Dados reais</span></div></article><article className="setting-card"><div className="setting-icon"><Globe2 size={19}/></div><div><h2>Domínio personalizado</h2><p>Disponível no Pro. O domínio é comprado por ti num registrador e ligado ao Product Hub.</p><span className="setting-note"><LockKeyhole size={14}/> Exclusivo Pro</span></div></article></section></div></main>;
}
