'use client';

import Link from 'next/link';
import { Check, LockKeyhole, Palette, Store, Sparkles, BarChart3, Package, Globe2 } from 'lucide-react';

const free=['Vitrine pública','Até 10 produtos','Logo, nome e descrição','Cores base','Layout grelha ou lista','Categorias básicas','Analytics básico'];
const pro=['Produtos ilimitados','Temas premium','Cores e tipografia avançadas','Layouts avançados','Banners e promoções','Produtos em destaque','Analytics avançado','Remover branding Product Hub','Domínio personalizado'];

export default function SettingsPage(){
 return <main className="settings-page"><div className="settings-wrap"><div className="page-heading"><div><span className="section-kicker">CONFIGURAÇÃO</span><h1>Definições</h1><p>Controla a tua conta, a vitrine e o plano do Product Hub num só lugar.</p></div></div><section className="settings-grid"><article className="setting-card"><div className="setting-icon"><Store size={19}/></div><div><h2>Personalizar vitrine</h2><p>Logo, identidade, cores, layout, cartões, botões, tipografia, categorias, destaques e conteúdo avançado.</p><Link className="primary" href="/dashboard">Abrir personalizador</Link></div></article><article className="setting-card"><div className="setting-icon"><Palette size={19}/></div><div><h2>Identidade visual</h2><p>O Product Hub usa apenas a linguagem visual definida para o produto: azul elétrico luminoso sobre dark.</p><span className="setting-note"><i/> Azul elétrico + Dark</span></div></article><article className="setting-card"><div className="setting-icon"><Package size={19}/></div><div><h2>Plano Free</h2><ul>{free.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul></div></article><article className="setting-card pro-card"><div className="setting-icon"><Sparkles size={19}/></div><div><h2>Plano Pro</h2><ul>{pro.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul><Link className="primary" href="/dashboard/billing">Ver Pro</Link></div></article><article className="setting-card"><div className="setting-icon"><BarChart3 size={19}/></div><div><h2>Analytics</h2><p>Visitas, visualizações, cliques, CTR, funil e desempenho por produto continuam centralizados na área Analytics.</p><Link href="/dashboard" className="view-store">Abrir Analytics</Link></div></article><article className="setting-card"><div className="setting-icon"><Globe2 size={19}/></div><div><h2>Domínio personalizado</h2><p>Disponível no Pro. O domínio é comprado por ti num registrador e ligado ao Product Hub.</p><span className="setting-note"><LockKeyhole size={14}/> Pro</span></div></article></section></div></main>;
}
