import type { Metadata } from 'next';
import { ArrowRight, Instagram, Mail, MapPin, Phone } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { StorefrontTracker, TrackedPurchaseLink } from '@/components/storefront-tracker';
import styles from '../storefront.module.css';

type Product={id:string;name:string;slug:string;description?:string|null;price?:number|null;currency?:string;purchase_url:string;provider?:string|null;category?:string|null;is_featured:boolean;images?:{storage_path:string}[]};
type StoreData={organization:{id:string;name:string;slug:string;description?:string|null;logo_url?:string|null};storefront:{status:string;template:string;theme_settings:Record<string,unknown>};products:Product[]};

async function getStore(slug:string){const s=await createClient();const {data,error}=await s.rpc('get_public_storefront',{store_slug:slug});if(error||!data?.organization)return null;return data as StoreData}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const store=await getStore(slug);if(!store)return{title:'Storefront | Product Hub'};const title=`${store.organization.name} | Product Hub`;const description=store.organization.description||`Explore the products from ${store.organization.name}.`;return{title,description,openGraph:{title,description,type:'website',images:store.organization.logo_url?[{url:store.organization.logo_url}]:[]},twitter:{card:'summary',title,description}}}
function money(p:Product){if(p.price==null)return null;try{return new Intl.NumberFormat('pt-PT',{style:'currency',currency:p.currency||'AOA'}).format(p.price)}catch{return`${p.currency||''} ${p.price}`.trim()}}
async function imageFor(path?:string|null){if(!path)return null;if(path.startsWith('http'))return path;const s=await createClient();return s.storage.from('product-images').getPublicUrl(path).data.publicUrl}
const str=(v:unknown, fallback='')=>typeof v==='string'?v:fallback;

export default async function Storefront({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{category?:string}>}){
 const {slug}=await params;const {category}=await searchParams;const store=await getStore(slug);if(!store)notFound();
 const all=store.products||[];const theme=store.storefront.theme_settings||{};const cats=Array.from(new Set(all.map(p=>p.category).filter(Boolean))) as string[];const products=category&&cats.includes(category)?all.filter(p=>p.category===category):all;
 const showFeatured=theme.showFeatured!==false;const featured=showFeatured?(products.find(p=>p.is_featured)||products[0]):null;const rest=products.filter(p=>p.id!==featured?.id);const layout=theme.layout==='list'?'list':'grid';const mode=theme.mode==='dark'?'dark':theme.mode==='soft'?'soft':'light';const radius=theme.radius==='small'?'small':theme.radius==='large'?'large':'medium';const card=theme.card==='elevated'?'elevated':theme.card==='bordered'?'bordered':'clean';const button=theme.button==='outline'?'outline':theme.button==='pill'?'pill':'solid';const font=theme.font==='serif'?'serif':theme.font==='rounded'?'rounded':'system';const header=theme.header==='split'?'split':theme.header==='minimal'?'minimal':'centered';const showPrices=theme.showPrices!==false;const showCategories=theme.showCategories!==false;const showBrand=theme.showProductHubBrand!==false;const accent=str(theme.accent,'#1f1f1f');const secondary=str(theme.secondary,'#6b7280');const background=str(theme.background,mode==='dark'?'#08090c':mode==='soft'?'#f3f2ed':'#fbfaf8');
 const bannerEnabled=theme.bannerEnabled===true;const bannerTitle=str(theme.bannerTitle,'');const bannerSubtitle=str(theme.bannerSubtitle,'');const bannerCta=str(theme.bannerCta,'');const bannerUrl=str(theme.bannerUrl,'');const bannerImage=str(theme.bannerImage,'');const contactEmail=str(theme.contactEmail,'');const contactPhone=str(theme.contactPhone,'');const location=str(theme.location,'');const instagram=str(theme.instagram,'');
 const featuredImage=await imageFor(featured?.images?.[0]?.storage_path);const restWithImages=await Promise.all(rest.map(async item=>({item,image:await imageFor(item.images?.[0]?.storage_path)})));
 return <main className={`${styles.page} ${styles[mode]} ${styles[`font-${font}`]} ${styles[`header-${header}`]} ${styles[`card-${card}`]} ${styles[`button-${button}`]} ${layout==='list'?styles.listLayout:''}`} style={{'--accent':accent,'--secondary':secondary,'--page-bg':background,'--card-radius':radius==='small'?'12px':radius==='large'?'28px':'19px'} as React.CSSProperties}>
 <div className={styles.inner}><StorefrontTracker organizationId={store.organization.id}/>
 <header className={styles.header}><div className={styles.identity}>{store.organization.logo_url?<img className={styles.logo} src={store.organization.logo_url} alt={store.organization.name}/>:<div className={styles.monogram}>{store.organization.name.slice(0,1).toUpperCase()}</div>}<h1 className={styles.name}>{store.organization.name}</h1>{store.organization.description&&<p className={styles.bio}>{store.organization.description}</p>}</div></header>
 {bannerEnabled&&bannerTitle&&<section className={styles.banner} style={bannerImage?{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.68),rgba(0,0,0,.16)),url(${bannerImage})`}:{}}><div><h2>{bannerTitle}</h2>{bannerSubtitle&&<p>{bannerSubtitle}</p>}{bannerCta&&(bannerUrl?<a href={bannerUrl}>{bannerCta}<ArrowRight size={15}/></a>:<span>{bannerCta}</span>)}</div></section>}
 {featured&&<section className={styles.featured}><div className={styles.featuredCopy}><span className={styles.eyebrow}>DESTAQUE</span><h2 className={styles.title}>{featured.name}</h2>{featured.description&&<p className={styles.description}>{featured.description}</p>}<div className={styles.buyLine}><TrackedPurchaseLink organizationId={store.organization.id} productId={featured.id} href={featured.purchase_url} className={styles.buy}>Comprar agora <ArrowRight size={17}/></TrackedPurchaseLink>{showPrices&&money(featured)&&<strong className={styles.price}>{money(featured)}</strong>}</div></div>{featuredImage&&<div className={styles.featuredArt}><img src={featuredImage} alt={featured.name}/></div>}</section>}
 {all.length>0&&showCategories&&<nav className={styles.nav} aria-label="Categorias"><Link href={`/store/${slug}`} className={`${styles.filter} ${!category?styles.filterActive:''}`}>Todos</Link>{cats.map(item=><Link href={`/store/${slug}?category=${encodeURIComponent(item)}`} className={`${styles.filter} ${category===item?styles.filterActive:''}`} key={item}>{item}</Link>)}</nav>}
 {rest.length>0&&<section className={styles.grid}>{restWithImages.map(({item,image})=>{const price=money(item);return <article className={styles.card} key={item.id}>{image?<Link className={styles.cardImage} href={`/store/${store.organization.slug}/${item.slug}`}><img src={image} alt={item.name}/></Link>:<Link className={`${styles.cardImage} ${styles.noImage}`} href={`/store/${store.organization.slug}/${item.slug}`}>{showBrand?'Product Hub':''}</Link>}<div className={styles.cardBody}>{showCategories&&item.category&&<span className={styles.label}>{item.category}</span>}<h3 className={styles.cardTitle}>{item.name}</h3>{item.description&&<p className={styles.cardDescription}>{item.description}</p>}<div className={styles.cardFooter}><TrackedPurchaseLink organizationId={store.organization.id} productId={item.id} href={item.purchase_url} className={styles.cardBuy}>Comprar <ArrowRight size={14}/></TrackedPurchaseLink>{showPrices&&price&&<strong className={styles.cardPrice}>{price}</strong>}</div></div></article>})}</section>}
 {!products.length&&<div className={styles.empty}><h2>Nenhum produto publicado.</h2><p>Esta categoria ainda não tem produtos disponíveis.</p></div>}
 {(contactEmail||contactPhone||location||instagram)&&<section className={styles.contact}><h2>Fala connosco</h2><div>{contactEmail&&<a href={`mailto:${contactEmail}`}><Mail size={16}/>{contactEmail}</a>}{contactPhone&&<a href={`tel:${contactPhone}`}><Phone size={16}/>{contactPhone}</a>}{location&&<span><MapPin size={16}/>{location}</span>}{instagram&&<a href={instagram} target="_blank" rel="noreferrer"><Instagram size={16}/>Instagram</a>}</div></section>}
 <footer className={styles.footer}>{showBrand&&<span>Product Hub</span>}<strong>{store.organization.name}</strong></footer></div></main>
}
