'use client';

import { useEffect, useState } from 'react';
import { Check, Megaphone, Save } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Props={organizationId:string;plan:string};
export function StorefrontAdvancedControls({organizationId,plan}:Props){
 const [v,setV]=useState({bannerEnabled:false,bannerTitle:'',bannerSubtitle:'',bannerCta:'',bannerUrl:'',bannerImage:'',contactEmail:'',contactPhone:'',location:'',instagram:''});
 const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{(async()=>{const s=createClient();const {data}=await s.from('storefronts').select('theme_settings').eq('organization_id',organizationId).maybeSingle();const t=(data?.theme_settings||{}) as Record<string,unknown>;setV(x=>{const next={...x};(Object.keys(x) as Array<keyof typeof x>).forEach(k=>{const value=t[String(k)];if(typeof value==='boolean'||typeof value==='string')next[k]=value as never});return next})})()},[organizationId]);
 const set=(k:keyof typeof v,value:string|boolean)=>setV(x=>({...x,[k]:value}));
 async function save(){if(plan!=='pro'){setError('Estas ferramentas são exclusivas do Pro.');return}setSaving(true);setError('');const s=createClient();const {data}=await s.from('storefronts').select('theme_settings').eq('organization_id',organizationId).maybeSingle();const theme={...(data?.theme_settings||{}),...v};const {error:e}=await s.from('storefronts').update({theme_settings:theme}).eq('organization_id',organizationId);if(e)setError(e.message);else{setSaved(true);setTimeout(()=>setSaved(false),1600)}setSaving(false)}
 const disabled=plan!=='pro';
 return <section className="panel" style={{marginTop:18,padding:22,opacity:disabled?.78:1}}><div style={{display:'flex',alignItems:'flex-start',justifyContent:'space-between',gap:18}}><div><div style={{display:'flex',alignItems:'center',gap:9}}><Megaphone size={17}/><h2 style={{margin:0}}>Experiência comercial</h2>{disabled&&<small>PRO</small>}</div><p style={{margin:'7px 0 0',color:'#8c95a4'}}>Banners promocionais e contactos aparecem diretamente na vitrine pública.</p></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14,marginTop:20}}><label>Ativar banner<select disabled={disabled} value={v.bannerEnabled?'true':'false'} onChange={e=>set('bannerEnabled',e.target.value==='true')}><option value="false">Desativado</option><option value="true">Ativado</option></select></label><label>Título do banner<input disabled={disabled} value={v.bannerTitle} onChange={e=>set('bannerTitle',e.target.value)} placeholder="Ex.: Nova coleção disponível"/></label><label>Subtítulo<input disabled={disabled} value={v.bannerSubtitle} onChange={e=>set('bannerSubtitle',e.target.value)} placeholder="Mensagem comercial curta"/></label><label>Texto do botão<input disabled={disabled} value={v.bannerCta} onChange={e=>set('bannerCta',e.target.value)} placeholder="Ver coleção"/></label><label>Link do botão<input disabled={disabled} value={v.bannerUrl} onChange={e=>set('bannerUrl',e.target.value)} placeholder="https://…"/></label><label>Imagem do banner<input disabled={disabled} value={v.bannerImage} onChange={e=>set('bannerImage',e.target.value)} placeholder="URL pública da imagem"/></label><label>Email de contacto<input disabled={disabled} value={v.contactEmail} onChange={e=>set('contactEmail',e.target.value)} placeholder="contacto@marca.com"/></label><label>Telefone<input disabled={disabled} value={v.contactPhone} onChange={e=>set('contactPhone',e.target.value)} placeholder="+244 …"/></label><label>Localização<input disabled={disabled} value={v.location} onChange={e=>set('location',e.target.value)} placeholder="Luanda, Angola"/></label><label>Instagram<input disabled={disabled} value={v.instagram} onChange={e=>set('instagram',e.target.value)} placeholder="https://instagram.com/…"/></label></div>{error&&<p style={{color:'#ff9e94'}}>{error}</p>}<button className="primary" onClick={save} disabled={disabled||saving} style={{marginTop:18}}>{saved?<><Check size={15}/> Guardado</>:<><Save size={15}/> {saving?'A guardar…':'Guardar experiência'}</>}</button></section>
}
