'use client';

import Link from 'next/link';
import { Suspense, useEffect, useState } from 'react';
import { Eye, EyeOff, ArrowRight, LockKeyhole } from 'lucide-react';
import { useRouter, useSearchParams } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

function withTimeout<T>(promise: PromiseLike<T>, ms: number, message: string): Promise<T> { return Promise.race([Promise.resolve(promise), new Promise<T>((_, reject) => setTimeout(() => reject(new Error(message)), ms))]); }

function LoginForm() {
  const router = useRouter(); const searchParams = useSearchParams();
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false); const [showPassword,setShowPassword]=useState(false); const [error,setError]=useState(''); const [remember,setRemember]=useState(false);
  useEffect(()=>{try{const saved=localStorage.getItem('product-hub-login-email');if(saved){setEmail(saved);setRemember(true)}}catch{}},[]);
  async function submit(e:React.FormEvent){e.preventDefault();if(loading)return;setLoading(true);setError('');const supabase=createClient();try{if(remember)localStorage.setItem('product-hub-login-email',email.trim());else localStorage.removeItem('product-hub-login-email');const {data,error:signInError}=await withTimeout(supabase.auth.signInWithPassword({email:email.trim(),password}),10000,'O servidor demorou demasiado a responder. Verifica a ligação e tenta novamente.');if(signInError)throw signInError;if(!data.user)throw new Error('A tua conta não pôde ser carregada.');let destination=searchParams.get('next')||'/dashboard';if(!searchParams.get('next')){try{const {data:membership,error:membershipError}=await withTimeout(supabase.from('organization_members').select('organization_id').eq('user_id',data.user.id).limit(1).maybeSingle(),5000,'workspace-timeout');if(!membershipError&&!membership?.organization_id)destination='/onboarding'}catch{destination='/dashboard'}}router.replace(destination);router.refresh();}catch(err){setError(err instanceof Error?err.message:'Não foi possível entrar. Verifica os teus dados.');setLoading(false)}}
  async function signInWithGoogle(){if(loading)return;setLoading(true);setError('');try{const origin=window.location.origin;const next=searchParams.get('next')||'/dashboard';const safeNext=next.startsWith('/')&&!next.startsWith('//')?next:'/dashboard';const {error}=await createClient().auth.signInWithOAuth({provider:'google',options:{redirectTo:`${origin}/auth/callback?next=${encodeURIComponent(safeNext)}`}});if(error)throw error;}catch(err){setError(err instanceof Error?err.message:'O acesso com Google não está disponível neste momento.');setLoading(false)}}
  return <main className="auth-page-premium auth-single"><video className="auth-video-full" autoPlay muted loop playsInline preload="auto" src="https://cdn.creativeclaw.co/u/51a597e8/videos/3effe537-1f62-440a-a12d-5c4d3cb12197.mp4" aria-hidden="true"/><section className="auth-panel-single"><div className="auth-card-premium"><div className="auth-brand-premium"><span className="hub-logo">P</span><strong>Product Hub</strong></div><div className="auth-heading"><span>PRODUCT HUB</span><h1>{loading?'A verificar…':'Iniciar sessão'}</h1><p>Entra no teu workspace e continua a construir a tua vitrine.</p></div><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com" required autoComplete="email" disabled={loading}/></label><label>Palavra-passe<div className="auth-password"><input type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required autoComplete="current-password" disabled={loading}/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Esconder palavra-passe':'Mostrar palavra-passe'} disabled={loading}>{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><label className="check auth-remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} disabled={loading}/> Lembrar-me</label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="primary auth-submit" disabled={loading}>{loading?<><LockKeyhole size={16}/> A verificar…</>:<>Entrar <ArrowRight size={16}/></>}</button></form><button className="social-login" type="button" onClick={signInWithGoogle} disabled={loading}>Continuar com Google</button><p className="auth-signup-prompt">Ainda não tens conta? <Link href="/signup">Criar conta agora</Link></p></div></section></main>;
}
export default function Login(){return <Suspense fallback={<main className="auth-page-premium auth-single"><div className="auth-panel-single"><div className="auth-card-premium"><p>A carregar o Product Hub…</p></div></div></main>}><LoginForm/></Suspense>}
