'use client';

import Link from 'next/link';
import { Suspense, useEffect, useState } from 'react';
import { Eye, EyeOff, LockKeyhole, ArrowRight, ShieldCheck } from 'lucide-react';
import { useRouter, useSearchParams } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

function withTimeout<T>(promise: PromiseLike<T>, ms: number, message: string): Promise<T> { return Promise.race([Promise.resolve(promise), new Promise<T>((_, reject) => setTimeout(() => reject(new Error(message)), ms))]); }

function LoginForm() {
  const router = useRouter(); const searchParams = useSearchParams();
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false); const [showPassword,setShowPassword]=useState(false); const [error,setError]=useState(''); const [remember,setRemember]=useState(false);
  useEffect(()=>{try{const saved=localStorage.getItem('product-hub-login-email');if(saved){setEmail(saved);setRemember(true)}}catch{}},[]);

  async function submit(e:React.FormEvent){e.preventDefault();if(loading)return;setLoading(true);setError('');const supabase=createClient();try{if(remember)localStorage.setItem('product-hub-login-email',email.trim());else localStorage.removeItem('product-hub-login-email');const result=await withTimeout(supabase.auth.signInWithPassword({email:email.trim(),password}),10000,'O servidor demorou demasiado a responder. Verifica a ligação e tenta novamente.');const {data,error:signInError}=result;if(signInError)throw signInError;if(!data.user)throw new Error('A tua conta não pôde ser carregada. Tenta entrar novamente.');let destination=searchParams.get('next')||'/dashboard';if(!searchParams.get('next')){try{const membershipResult=await withTimeout(supabase.from('organization_members').select('organization_id').eq('user_id',data.user.id).limit(1).maybeSingle(),5000,'workspace-timeout');const {data:membership,error:membershipError}=membershipResult;if(!membershipError&&!membership?.organization_id)destination='/onboarding'}catch{destination='/dashboard'}}setLoading(false);router.replace(destination);router.refresh();}catch(err){setError(err instanceof Error?err.message:'Não foi possível entrar. Verifica os teus dados e tenta novamente.');setLoading(false)}}

  async function signInWithGoogle(){if(loading)return;setLoading(true);setError('');try{const {error}=await createClient().auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/auth/callback?next=/dashboard`}});if(error)throw error;}catch(err){setError(err instanceof Error?err.message:'Não foi possível iniciar o login com Google.');setLoading(false)}}

  return <main className="auth-page-premium"><section className="auth-visual" aria-hidden="true">{loading?<video className="auth-video" autoPlay muted loop playsInline preload="auto" src="https://cdn.creativeclaw.co/u/51a597e8/videos/3effe537-1f62-440a-a12d-5c4d3cb12197.mp4"/>:<div className="auth-static-visual"><div className="auth-orb auth-orb-one"/><div className="auth-orb auth-orb-two"/><div className="auth-grid"/><div className="auth-product-mark"><span className="hub-logo">P</span></div></div>}<div className="auth-visual-copy"><span className="auth-kicker">PRODUCT HUB / WORKSPACE</span><strong>O teu catálogo.<br/>Num só lugar.</strong><p>Cria, organiza e apresenta os teus produtos numa experiência pensada para vender melhor.</p><div className="auth-trust"><ShieldCheck size={15}/> Ambiente protegido para o teu negócio</div></div></section><section className="auth-panel"><div className="auth-card-premium"><div className="auth-brand-premium"><span className="hub-logo">P</span><strong>Product Hub</strong></div><div className="auth-heading"><span>Bem-vindo de volta</span><h1>{loading?'A preparar o teu espaço…':'Entra no teu workspace.'}</h1><p>{loading?'Estamos a validar a tua sessão com segurança.':'Continua exatamente de onde paraste.'}</p></div><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com" required autoComplete="email" disabled={loading}/></label><label>Palavra-passe<div className="auth-password"><input type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" required autoComplete="current-password" disabled={loading}/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Esconder palavra-passe':'Mostrar palavra-passe'} disabled={loading}>{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><div className="auth-row"><label className="check"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} disabled={loading}/> Lembrar-me</label><Link href="/forgot-password">Esqueci-me da palavra-passe</Link></div>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="primary auth-submit" disabled={loading}>{loading?<><LockKeyhole size={16}/> A verificar…</>:<>Entrar no Product Hub <ArrowRight size={16}/></>}</button></form><div className="auth-divider"><span>ou</span></div><button className="social-login" type="button" onClick={signInWithGoogle} disabled={loading}>Continuar com Google</button><small>Ainda não tens conta? <Link href="/signup">Criar conta</Link></small></div></section></main>;
}
export default function Login(){return <Suspense fallback={<main className="auth-page-premium"><section className="auth-panel"><div className="auth-card-premium"><p>A carregar o Product Hub…</p></div></section></main>}><LoginForm/></Suspense>}
