'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, UserPlus } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

export default function Signup(){
 const router=useRouter(); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [success,setSuccess]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();if(loading)return;setLoading(true);setMessage('');setSuccess(false);try{if(password.length<8)throw new Error('A palavra-passe deve ter pelo menos 8 caracteres.');const supabase=createClient();const {data,error}=await supabase.auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim()}}});if(error)throw error;if(data.session){setSuccess(true);setMessage('Conta criada. A preparar a tua vitrine…');router.replace('/onboarding');router.refresh();}else{setSuccess(true);setMessage('Conta criada. Confirma o teu email e depois inicia sessão.');}}catch(err){setMessage(err instanceof Error?err.message:'Não foi possível criar a conta. Tenta novamente.');}finally{setLoading(false)}}
 return <main className="auth-page-premium auth-single"><video className="auth-video-full" autoPlay muted loop playsInline preload="auto" src="https://cdn.creativeclaw.co/u/51a597e8/videos/79ba29f5-88cd-4a18-8b58-8a9e2abd9d95.mp4" aria-hidden="true"/><div className="auth-video-shade"/><section className="auth-panel-single"><div className="auth-card-premium"><div className="auth-brand-premium"><span className="hub-logo">P</span><strong>Product Hub</strong></div><div className="auth-heading"><span>PRODUCT HUB / NOVA CONTA</span><h1>Criar conta</h1><p>Cria o teu workspace e começa a montar a tua vitrine.</p></div><form onSubmit={submit}><label>Nome completo<input value={name} onChange={e=>setName(e.target.value)} placeholder="João Silva" required autoComplete="name" disabled={loading}/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com" required autoComplete="email" disabled={loading}/></label><label>Palavra-passe<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Pelo menos 8 caracteres" minLength={8} required autoComplete="new-password" disabled={loading}/></label>{message&&<div className={`auth-error ${success?'auth-success':''}`} role="status">{message}</div>}<button className="primary auth-submit" disabled={loading}>{loading?<><UserPlus size={16}/> A criar…</>:<>Criar conta <ArrowRight size={16}/></>}</button></form><p className="auth-signup-prompt">Já tens uma conta? <Link href="/login">Iniciar sessão</Link></p></div></section></main>;
}
