create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  logo_url text,
  website_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner' check (role in ('owner','admin','member')),
  created_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table if not exists public.storefronts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null unique references public.organizations(id) on delete cascade,
  status text not null default 'draft' check (status in ('draft','published','unpublished')),
  template text not null default 'editorial',
  theme_settings jsonb not null default '{}'::jsonb,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  slug text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, slug)
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  category_id uuid references public.categories(id) on delete set null,
  name text not null,
  slug text not null,
  description text,
  price numeric(14,2),
  currency text not null default 'AOA',
  purchase_url text not null,
  provider text,
  is_featured boolean not null default false,
  is_published boolean not null default false,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, slug)
);

create table if not exists public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  storage_path text not null,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  event_type text not null check (event_type in ('store_view','product_view','product_click')),
  session_id text,
  referrer text,
  device_type text,
  created_at timestamptz not null default now()
);

create index if not exists idx_members_user on public.organization_members(user_id);
create index if not exists idx_products_org_position on public.products(organization_id, position);
create index if not exists idx_products_org_published on public.products(organization_id, is_published);
create index if not exists idx_product_images_product_position on public.product_images(product_id, position);
create index if not exists idx_analytics_org_created on public.analytics_events(organization_id, created_at desc);

create or replace function public.is_org_member(target_org uuid)
returns boolean language sql security definer set search_path = public stable as $$
  select exists (
    select 1 from public.organization_members m
    where m.organization_id = target_org and m.user_id = auth.uid()
  );
$$;

create or replace function public.is_org_admin(target_org uuid)
returns boolean language sql security definer set search_path = public stable as $$
  select exists (
    select 1 from public.organization_members m
    where m.organization_id = target_org and m.user_id = auth.uid() and m.role in ('owner','admin')
  );
$$;

grant execute on function public.is_org_member(uuid) to authenticated;
grant execute on function public.is_org_admin(uuid) to authenticated;

alter table public.profiles enable row level security;
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.storefronts enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles for all using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists org_member_read on public.organizations;
create policy org_member_read on public.organizations for select using (public.is_org_member(id));
drop policy if exists org_admin_write on public.organizations;
create policy org_admin_write on public.organizations for all using (public.is_org_admin(id)) with check (public.is_org_admin(id));

drop policy if exists members_read on public.organization_members;
create policy members_read on public.organization_members for select using (public.is_org_member(organization_id));
drop policy if exists members_owner_write on public.organization_members;
create policy members_owner_write on public.organization_members for all using (public.is_org_admin(organization_id)) with check (public.is_org_admin(organization_id));

drop policy if exists storefront_member_all on public.storefronts;
create policy storefront_member_all on public.storefronts for all using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));

drop policy if exists category_member_all on public.categories;
create policy category_member_all on public.categories for all using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));

drop policy if exists product_member_all on public.products;
create policy product_member_all on public.products for all using (public.is_org_member(organization_id)) with check (public.is_org_member(organization_id));

drop policy if exists image_member_all on public.product_images;
create policy image_member_all on public.product_images for all using (
  exists (select 1 from public.products p where p.id = product_id and public.is_org_member(p.organization_id))
) with check (
  exists (select 1 from public.products p where p.id = product_id and public.is_org_member(p.organization_id))
);

drop policy if exists analytics_member_read on public.analytics_events;
create policy analytics_member_read on public.analytics_events for select using (public.is_org_member(organization_id));
drop policy if exists analytics_insert_public on public.analytics_events;
create policy analytics_insert_public on public.analytics_events for insert with check (
  event_type in ('store_view','product_view','product_click')
  and exists (select 1 from public.storefronts s where s.organization_id = organization_id and s.status = 'published')
);

create or replace function public.get_public_storefront(store_slug text)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'organization', to_jsonb(o),
    'storefront', to_jsonb(s),
    'products', coalesce((select jsonb_agg(jsonb_build_object(
      'id',p.id,'name',p.name,'slug',p.slug,'description',p.description,'price',p.price,'currency',p.currency,
      'purchase_url',p.purchase_url,'provider',p.provider,'is_featured',p.is_featured,
      'images',coalesce((select jsonb_agg(jsonb_build_object('storage_path',pi.storage_path) order by pi.position)
        from public.product_images pi where pi.product_id=p.id),'[]'::jsonb)
    ) order by p.is_featured desc, p.position, p.created_at desc)
      from public.products p where p.organization_id=o.id and p.is_published = true),'[]'::jsonb)
  )
  from public.organizations o
  join public.storefronts s on s.organization_id=o.id
  where o.slug=store_slug and s.status='published'
  limit 1;
$$;

grant execute on function public.get_public_storefront(text) to anon, authenticated;
