'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowUpRight, BarChart3, Check, Copy, ExternalLink, LayoutDashboard, LogOut, Package, Plus, Search, Settings, Store, Users, Zap } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { DashboardCustomizer } from '@/components/dashboard-customizer';
import { DashboardHero } from '@/components/dashboard-hero';

const supabase=createClient();
const nav=[['overview','Visão geral',LayoutDashboard],['products','Produtos',Package],['storefront','Vitrine',Store],['analytics','Analytics',BarChart3],['settings','Definições',Settings]] as const;
type Product={id:string;name:string;slug:string;description:string|null;price:number|null;currency:string|null;purchase_url:string|null;provider:string|null;is_featured:boolean;is_published:boolean;position:number;created_at:string;updated_at:string;product_images?:{id:string;storage_path:string;position:number}[]};

export default function DashboardPage(){
 const [user,setUser]=useState<any>(null),[org,setOrg]=useState<any>(null),[products,setProducts]=useState<Product[]>([]),[events,setEvents]=useState<any[]>([]),[storefront,setStorefront]=useState<any>(null),[active,setActive]=useState('overview'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[range,setRange]=useState(30),[copied,setCopied]=useState(false);
 useEffect(()=>{let mounted=true;(async()=>{try{const {data:{user:u}}=await supabase.auth.getUser();if(!u){if(mounted)setLoading(false);return}const {data:m,error:me}=await supabase.from('organization_members').select('organization_id').eq('user_id',u.id).limit(1).maybeSingle();if(me)throw me;if(!m?.organization_id){setError('Ainda não tens uma organização configurada.');return}const id=m.organization_id;const [{data:o,error:oe},{data:p,error:pe},{data:s,error:se},{data:e,error:ee}]=await Promise.all([supabase.from('organizations').select('*').eq('id',id).single(),supabase.from('products').select('*,product_images(id,storage_path,position)').eq('organization_id',id).order('created_at',{ascending:false}),supabase.from('storefronts').select('*').eq('organization_id',id).limit(1).maybeSingle(),supabase.from('analytics_events').select('*').eq('organization_id',id).gte('created_at',new Date(Date.now()-90*86400000).toISOString()).order('created_at',{ascending:true})]);if(oe)throw oe;if(pe)throw pe;if(se)throw se;if(ee)throw ee;if(mounted){setUser(u);setOrg(o);setProducts((p||[]) as Product[]);setStorefront(s);setEvents(e||[])}}catch(err:any){if(mounted)setError(err?.message||'Não foi possível carregar o dashboard.')}finally{if(mounted)setLoading(false)}})();return()=>{mounted=false}},[]);
 const ev=useMemo(()=>events.filter(e=>Date.now()-new Date(e.created_at).getTime()<=range*86400000),[events,range]);
 const views=ev.filter(e=>['store_view','view','page_view'].includes(e.event_type)).length,clicks=ev.filter(e=>['product_click','click'].includes(e.event_type)).length,productViews=ev.filter(e=>e.event_type==='product_view').length,ctr=views?clicks/views*100:0;
 const imageUrl=(p:Product)=>{const i=p.product_images?.slice().sort((a,b)=>a.position-b.position)[0];return i?supabase.storage.from('product-images').getPublicUrl(i.storage_path).data.publicUrl:null};
 const logout=async()=>{await supabase.auth.signOut();window.location.href='/login'};
 if(loading)return <div className="app-shell"><main className="main-shell"><div className="page-content"><div className="dashboard-loading"><div className="loading-orb"><Package size={22}/></div><strong>A preparar o teu espaço</strong><span>Estamos a organizar os teus dados…</span></div></div></main></div>;
 if(error)return <div className="app-shell"><main className="main-shell"><div className="page-content"><div className="empty">{error}</div></div></main></div>;
 return <div className="app-shell"><aside className="sidebar"><div className="sidebar-brand"><div className="hub-logo">P</div><div><strong>Product Hub</strong><small>Commerce workspace</small></div></div><div className="org-switch"><div className="org-avatar">{(org?.name?.[0]||'W').toUpperCase()}</div><div><strong>{org?.name||'Workspace'}</strong><small>Workspace ativo</small></div><Users size={15}/></div><div className="side-label">Workspace</div><nav className="side-nav">{nav.map(([k,l,I])=><button key={k} className={active===k?'active':''} onClick={()=>setActive(k)}><I size={17}/><span>{l}</span></button>)}</nav><div className="sidebar-spacer"/><div className="plan-card"><div className="plan-icon"><Zap size={15}/></div><div><strong>Hub ativo</strong><span>Catálogo, vitrine e dados num só lugar.</span></div></div><button className="help" onClick={logout}><span>↪</span><span>Sair</span><LogOut size={14}/></button><div className="user-row"><div className="avatar">{(user?.email?.[0]||'U').toUpperCase()}</div><div><strong>{user?.email?.split('@')[0]||'Utilizador'}</strong><small>{user?.email||''}</small></div></div></aside><main className="main-shell"><header className="topbar"><div><span className="topbar-kicker">PRODUCT HUB</span><span className="topbar-title">{nav.find(n=>n[0]===active)?.[1]}</span></div><div className="topbar-actions">{org?.slug&&<a className="view-store" href={`/store/${org.slug}`} target="_blank" rel="noreferrer"><ExternalLink size={14}/> Abrir vitrine</a>}<div className="topbar-avatar">{(user?.email?.[0]||'U').toUpperCase()}</div></div></header><div className="page-content">
 {active==='overview'&&<><DashboardHero name={user?.user_metadata?.name||user?.email?.split('@')[0]} views={views} clicks={clicks} products={products.length}/>{org?.slug&&<div className="store-url"><div><span className="live-dot"/><Store size={15}/><span>{window.location.origin}/store/{org.slug}</span></div><div><button onClick={()=>{navigator.clipboard?.writeText(`${window.location.origin}/store/${org.slug}`);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?<Check size={14}/>:<Copy size={14}/>} {copied?'Copiado':'Copiar link'}</button><a href={`/store/${org.slug}`} target="_blank" rel="noreferrer"><ArrowUpRight size={14}/> Visualizar</a></div></div>}<section className="dashboard-section"><div className="section-heading"><div><h2>O teu negócio hoje</h2><p>Uma leitura rápida do que está a acontecer.</p></div><div className="range-control">{[7,30,90].map(n=><button key={n} className={range===n?'selected':''} onClick={()=>setRange(n)}>{n}d</button>)}</div></div><div className="metric-grid four"><Metric icon={<Activity size={17}/>} label="Visitas" value={String(views)} hint={`${range} dias`} trend="Tráfego"/><Metric icon={<BarChart3 size={17}/>} label="Cliques" value={String(clicks)} hint="interações" trend="Ação"/><Metric icon={<Package size={17}/>} label="Produtos" value={String(products.length)} hint="catálogo" trend="Inventário"/><Metric icon={<Zap size={17}/>} label="CTR" value={`${ctr.toFixed(1)}%`} hint="cliques / visitas" trend="Conversão"/></div></section><section className="panel product-panel"><div className="panel-head"><div><h2>Produtos recentes</h2><span>Imagem, descrição, preço e compra</span></div><button onClick={()=>setActive('products')}>Ver catálogo <ArrowUpRight size={14}/></button></div><div className="product-feed">{products.slice(0,5).map(p=><ProductRow key={p.id} p={p} imageUrl={imageUrl(p)}/>)}{!products.length&&<div className="empty">Ainda não tens produtos.</div>}</div></section></>}
 {active==='products'&&<><div className="page-heading product-heading"><div><span className="section-kicker">CATÁLOGO</span><h1>Produtos</h1><p>Cada produto mostra a imagem, descrição, preço e ação de compra.</p></div><a className="primary" href="/dashboard/products/new"><Plus size={15}/> Adicionar produto</a></div><div className="search"><Search size={15}/><input id="product-search" placeholder="Pesquisar produto…" onChange={e=>{const v=e.target.value.toLowerCase();document.querySelectorAll<HTMLElement>('[data-product-name]').forEach(x=>x.style.display=x.dataset.productName!.includes(v)?'':'none')}}/></div><div className="product-catalog">{products.map(p=><ProductCard key={p.id} p={p} imageUrl={imageUrl(p)}/>)}</div></>}
 {active==='storefront'&&storefront?.slug&&org?.id&&<DashboardCustomizer organizationId={org.id} storefrontPath={`/store/${org.slug}`}/>} {active==='analytics'&&<Analytics events={events} range={range} setRange={setRange} views={views} productViews={productViews} clicks={clicks} ctr={ctr}/>} {active==='settings'&&<SettingsPanel org={org}/>}</div></main></div>
}
function Metric({icon,label,value,hint,trend}:{icon:React.ReactNode;label:string;value:string;hint:string;trend:string}){return <div className="metric"><div className="metric-top"><div className="metric-icon">{icon}</div><span>{trend}</span></div><small>{label}</small><strong>{value}</strong><em>{hint}</em></div>}
function ProductRow({p,imageUrl}:{p:Product;imageUrl:string|null}){return <div className="product-feed-row"><div className="feed-image">{imageUrl?<img src={imageUrl} alt=""/>:<Package size={20}/>}</div><div className="feed-main"><strong>{p.name}</strong><p>{p.description||'Sem descrição adicionada.'}</p></div><strong className="feed-price">{p.price!=null?`${Number(p.price).toLocaleString('pt-PT')} ${p.currency||'AOA'}`:'Preço sob consulta'}</strong>{p.purchase_url?<a className="feed-buy" href={p.purchase_url} target="_blank" rel="noreferrer">Comprar <ArrowUpRight size={13}/></a>:<span className="no-link">Sem link</span>}</div>}
function ProductCard({p,imageUrl}:{p:Product;imageUrl:string|null}){return <article className="dashboard-product-card" data-product-name={p.name.toLowerCase()}><div className="dashboard-product-image">{imageUrl?<img src={imageUrl} alt={p.name}/>:<Package size={30}/>}<span className={p.is_published?'published':'draft'}>{p.is_published?'Publicado':'Rascunho'}</span></div><div className="dashboard-product-body"><small>{p.provider||'Produto'}{p.is_featured?' · Destaque':''}</small><h2>{p.name}</h2>{p.description&&<p>{p.description}</p>}<div className="dashboard-product-footer"><strong>{p.price!=null?`${Number(p.price).toLocaleString('pt-PT')} ${p.currency||'AOA'}`:'Preço sob consulta'}</strong>{p.purchase_url?<a href={p.purchase_url} target="_blank" rel="noreferrer">Comprar <ArrowUpRight size={14}/></a>:<span className="no-link">Adiciona um link de compra</span>}</div></div></article>}
function Analytics({events,range,setRange,views,productViews,clicks,ctr}:any){const buckets=Array.from({length:7},(_,i)=>{const end=Date.now()-(6-i)*Math.ceil(range/7)*86400000,start=end-Math.ceil(range/7)*86400000;return{label:new Date(end).toLocaleDateString('pt-PT',{day:'2-digit',month:'short'}),value:events.filter((e:any)=>{const t=new Date(e.created_at).getTime();return t>=start&&t<end}).length}});const max=Math.max(1,...buckets.map(b=>b.value));return <><div className="page-heading"><div><span className="section-kicker">INSIGHTS</span><h1>Analytics</h1><p>Comportamento real da tua vitrine.</p></div><div className="range-control">{[7,30,90].map(n=><button key={n} className={range===n?'selected':''} onClick={()=>setRange(n)}>{n} dias</button>)}</div></div><div className="metric-grid four"><Metric icon={<Activity size={16}/>} label="Visitas" value={String(views)} hint="page views" trend="Tráfego"/><Metric icon={<Package size={16}/>} label="Visualizações" value={String(productViews)} hint="produtos vistos" trend="Interesse"/><Metric icon={<BarChart3 size={16}/>} label="Cliques" value={String(clicks)} hint="interações" trend="Ação"/><Metric icon={<Zap size={16}/>} label="CTR" value={`${ctr.toFixed(1)}%`} hint="cliques / visitas" trend="Eficiência"/></div><div className="panel chart-panel"><div className="panel-head"><div><h2>Atividade</h2><span>Eventos registados por período</span></div></div><div className="chart-area">{buckets.map((b,i)=><div className="chart-column" key={i}><div className="chart-bar" style={{height:`${Math.max(7,b.value/max*100)}%`}}/><small>{b.label}</small></div>)}</div></div></>}
function SettingsPanel({org}:{org:any}){const [name,setName]=useState(org?.name||''),[description,setDescription]=useState(org?.description||''),[saved,setSaved]=useState(false);async function save(){const {error}=await supabase.from('organizations').update({name,description}).eq('id',org.id);if(!error){setSaved(true);setTimeout(()=>setSaved(false),1500)}}return <><div className="page-heading"><div><h1>Definições</h1><p>Identidade do teu workspace.</p></div></div><section className="panel settings-panel"><label>Nome<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Descrição<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4}/></label><button className="primary" onClick={save}>{saved?'Guardado':'Guardar alterações'}</button></section></>}
