import type { Metadata } from 'next';
import { ArrowLeft, ArrowRight } from 'lucide-react';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createClient } from '@/lib/supabase/server';
import { StorefrontTracker, TrackedPurchaseLink } from '@/components/storefront-tracker';
import styles from '../../storefront.module.css';

type Product={id:string;name:string;slug:string;description?:string|null;price?:number|null;currency?:string;purchase_url:string;category?:string|null;images?:{storage_path:string}[]};
type StoreData={organization:{id:string;name:string;slug:string;description?:string|null;logo_url?:string|null};storefront:{status:string;theme_settings:Record<string,unknown>};products:Product[]};
async function getStore(slug:string){const s=await createClient();const {data,error}=await s.rpc('get_public_storefront',{store_slug:slug});if(error||!data?.organization)return null;return data as StoreData}
function money(p:Product){if(p.price==null)return null;try{return new Intl.NumberFormat('pt-PT',{style:'currency',currency:p.currency||'AOA'}).format(p.price)}catch{return`${p.currency||''} ${p.price}`.trim()}}
async function imageFor(path?:string|null){if(!path)return null;if(path.startsWith('http'))return path;const s=await createClient();return s.storage.from('product-images').getPublicUrl(path).data.publicUrl}
export async function generateMetadata({params}:{params:Promise<{slug:string;productSlug:string}>}):Promise<Metadata>{const {slug,productSlug}=await params;const store=await getStore(slug);const product=store?.products?.find(p=>p.slug===productSlug);if(!store||!product)return{title:'Produto | Product Hub'};return{title:`${product.name} | ${store.organization.name}`,description:product.description||`Conhece ${product.name}.`}}
export default async function ProductPage({params}:{params:Promise<{slug:string;productSlug:string}>}){const {slug,productSlug}=await params;const store=await getStore(slug);if(!store)notFound();const product=store.products.find(p=>p.slug===productSlug);if(!product)notFound();const image=await imageFor(product.images?.[0]?.storage_path);const theme=store.storefront.theme_settings||{};const accent=typeof theme.accent==='string'?theme.accent:'#1f1f1f';const mode=theme.mode==='dark'?'dark':theme.mode==='soft'?'soft':'light';return <main className={`${styles.page} ${styles[mode]}`} style={{'--accent':accent} as React.CSSProperties}><div className={styles.inner}><StorefrontTracker organizationId={store.organization.id}/><Link className={styles.productBack} href={`/store/${slug}`}><ArrowLeft size={15}/> Voltar à vitrine</Link><article className={styles.productDetail}>{image&&<div className={styles.productDetailImage}><img src={image} alt={product.name}/></div>}<div className={styles.productDetailCopy}>{product.category&&<span className={styles.label}>{product.category}</span>}<h1 className={styles.productDetailTitle}>{product.name}</h1>{product.description&&<p className={styles.productDetailDescription}>{product.description}</p>}<div className={styles.productDetailAction}><TrackedPurchaseLink organizationId={store.organization.id} productId={product.id} href={product.purchase_url} className={styles.buy}>Comprar <ArrowRight size={16}/></TrackedPurchaseLink>{money(product)&&<strong className={styles.productDetailPrice}>{money(product)}</strong>}</div></div></article></div></main>}
